pipeline:
  name: SamplePipeline
  identifier: SamplePipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test and Build
        identifier: Test_and_Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: test
                  identifier: test
                  spec:
                    shell: Sh
                    command: |-
                      npm install
                      npm test
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1704185770842
        repoName: Flows-Convergence/todo-app-example
        build: <+input>
