pipeline:
  name: SamplePipeline
  identifier: SamplePipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test and Build
        identifier: Test_and_Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: test
                  identifier: test
                  spec:
                    shell: Sh
                    command: |-
                      npm install
                      npm test
    - stage:
        name: deploy_prod
        identifier: Deploy_Stage
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: New_Service
          environment:
            environmentRef: Dev_Enironment
            deployToAll: false
            infrastructureDefinitions:
              - identifier: altafSampleInfra1
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1704185770842
        repoName: Flows-Convergence/todo-app-example
        build: <+input>
  notificationRules:
    - name: DevRev Webhook
      identifier: DevRev_Webhook
      pipelineEvents:
        - type: AllEvents
        - type: PipelineStart
        - type: PipelineEnd
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: StageFailed
        - type: StageSuccess
        - type: StageStart
        - type: StepFailed
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: https://api.devrev.ai/hidden/dev-orgs/DEV-1AJCBQFDh/event-source-webhooks/custom/712b8496-add8-4572-91f8-76f6f54b5760?branch=<+trigger.targetBranch>&prTitle=<+trigger.prTitle>&prBody=<+eventPayload.pull_request.body>&eventType=<+trigger.header['X-GitHub-Event']>&commit=<+eventPayload.head_commit.message>
      enabled: true
